---

- name: Ubuntu | Install prerequisites
  raw: "{{ item }}"
  with_items:
    - sleep 10
    - apt-get update -qq
    - apt-get install -qq -y python2.7 sudo
  become: true

- name: Ubuntu | Configure defaults
  raw: sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
  tags:
    - update-alternatives
